### ISSUE TITLE
代理池没有生效

### ISSUE THREAD

**Issue by restaurant8** [pplulee/appleid_auto#24]
代理池显示上次使用时间‘2000-01-01 00:00:00’ 没有变化 执行任务也提示 IP被拉黑。请问应该怎么排错。
代理池只有一个代理  启用状态 用其他方式（aws开机的一个面板）亲测代理正常使用

**Comment by pplulee** [comment]
执行任务时提示使用代理了吗？

**Comment by restaurant8** [comment]
我直接重装解决了，感谢百忙中回复
