### ISSUE TITLE
hi，该项目可以只部署后端吗？仅调用api

### ISSUE THREAD

**Issue by googidaddy** [pplulee/appleid_auto#26]
无须前端页面展示，调用后端api获取账号密码，仅后端可以吗？

**Comment by pplulee** [comment]
前端提供API功能以及账号/任务管理的功能，如果不想部署前端 可以fork backend分支，修改[后端主程序](https://github.com/pplulee/appleid_auto/blob/backend/backend/unblocker/main.py) ，传入对应参数即可启动。
