### ISSUE TITLE
保存账号时显示后端接口异常

### ISSUE THREAD

**Issue by googidaddy** [pplulee/appleid_auto#27]
点击重启任务，显示后端接口异常
.env里的webdriver 4444地址能访问
前后端都在一个服务器上

**Comment by pplulee** [comment]
1. 在env内启用后端接口后，请重启一次appleauto容器
2. 如修改了接口端口，请保证未被占用
如果仍有问题，请提供env与appleauto日志截图

**Comment by googidaddy** [comment]
刚刚收到tg bot的消息：xxx,无法处理请求，可能是服务器IP被拉黑

**Comment by pplulee** [comment]
所以你有什么疑问？

> 刚刚收到tg bot的消息：xxx,无法处理请求，可能是服务器IP被拉黑

**Comment by googidaddy** [comment]
![image](https://github.com/pplulee/appleid_auto/assets/63139246/cbb003a4-8ff0-40d4-a3e5-45613f60e295)
所以这样代表是没问题，只是服务器ip被拉黑了对吗？

**Comment by pplulee** [comment]
WebDriver不是后端，你指定了后端使用4444端口，这与WebDriver冲突了。后端相关设置保持默认即可，无特殊情况不需要修改。
