### ISSUE TITLE
感谢作者，拯救了我

### ISSUE THREAD

**Issue by vonaxs** [pplulee/appleid_auto#28]
别人总是开启双重认证
我被逼疯了
一天让我关10回双重认证
这个项目不要太爽

准备捐赠50刀。

**Comment by pplulee** [comment]
感谢支持

**Comment by vonaxs** [comment]
已捐

**Comment by pplulee** [comment]
> 已捐

可以留个联系方式，送你个Pro的个人版

**Comment by vonaxs** [comment]
> > 已捐
> 
> 可以留个联系方式，送你个Pro的个人版
cutedoge@skypure.xyz
