### ISSUE TITLE
NameError: name 'driver' is not defined. Did you mean: 'webdriver'?

### ISSUE THREAD

**Issue by zyqwks** [pplulee/appleid_auto#3]
NameError: name 'driver' is not defined. Did you mean: 'webdriver'?
请问运行报这个错误怎么弄

CRITICAL:root:Webdriver调用失败
04:35:07 [ERROR] Webdriver调用失败

**Comment by pplulee** [comment]
WebDriver调用失败了，检查一下WebDriver面板能否访问，URL是否正确

**Comment by zyqwks** [comment]
WebDriver面板是那个selenium/standalone-chrome端口4444的这个吗

**Comment by zyqwks** [comment]
是这个的话，那还真是访问不了

**Comment by pplulee** [comment]
是4444端口

**Comment by zyqwks** [comment]
我按照他教程弄的，是哪里不正确吗
docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.5.3-20221024

**Comment by pplulee** [comment]
你自己检查一下端口为什么不通吧

**Comment by zyqwks** [comment]
好的，谢谢

**Comment by zyqwks** [comment]
selenium/standalone-chrome日志报这个是什么情况，麻烦帮忙看看
![image](https://user-images.githubusercontent.com/112051946/199942365-07d327f6-d1a6-4e88-b26d-93cb5f3398cd.png)

**Comment by pplulee** [comment]
selenium一般不会出问题，有没有可能是你防火墙没开之类的？

**Comment by zyqwks** [comment]
我知道了，是服务器ip被苹果干掉了

**Comment by pplulee** [comment]
服务器IP被拉黑不会导致4444无法访问

**Comment by zyqwks** [comment]
嗯，现在4444可以访问，就是现在轮到selenium报上面的错，就是服务器IP被拉黑
