### ISSUE TITLE
共享账号被锁

### ISSUE THREAD

**Issue by Nemo8454** [pplulee/appleid_auto#30]
作者你好，请问共享账号是如何生成的？有没有绑定的实体账号数据？可以加个联系方式吗？

**Comment by pplulee** [comment]
你说的“共享账号”是指分享页吗？创建分享页时可以选择多个账号。商业版有账号兑换码和按标签生成分享页的功能。你可以加TG群然后联系我。

**Comment by Nemo8454** [comment]
不好意思，我加了群组，不知道你是哪位
