### ISSUE TITLE
这个库可以解决 apple id 锁定问题吗？

### ISSUE THREAD

**Issue by 954-Ivory** [pplulee/appleid_auto#4]
iforgot.apple.com 提示：

`你将可以在 13 天后重设密码`

苹果这密码找回机制，真的是世界一绝。

**Comment by pplulee** [comment]
脚本只是模拟浏览器操作，无法绕过限制

如有相关页面html存档可以发在这里，我可以加入错误提示

**Comment by 954-Ivory** [comment]
> 脚本只是模拟浏览器操作，无法绕过限制
> 
> 如有相关页面html存档可以发在这里，我可以加入错误提示

好的，可能是我误解了。

刚大致看了下相关的 python 代码，主要用来做账号的批量管理？

我以为有针对密码重置模块的逃逸方法。(T v T)

~~或许可以考虑细化一下 README.md~~
