### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by qwinwin** [pplulee/appleid_auto#6]
目前tg通知好像只有在解锁成功时才会通知，建议增加在失败时也通知 比如：ip被封等ERROR出现时也通知

**Comment by pplulee** [comment]
是的，设计的是只有在修改密码时发送通知，不然定时N分钟发送一次消息会有点“吵”。
发送错误信息我觉得可以，下次加一下功能，或者你有兴趣的话开个pr也行

**Comment by qwinwin** [comment]
ok 开了个pr就加了一条我目前遇到的
